DROP DATABASE if EXISTS unesp_db;
CREATE DATABASE if NOT EXISTS unesp_db;
USE unesp_db;

DROP TABLE if EXISTS users;
CREATE TABLE if NOT EXISTS users (
	id INT(11) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(id),
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	ativo INT(11) NOT NULL DEFAULT 1
);